### ISSUE TITLE
通过header location让微信重定向不起作用，不做跳转

### ISSUE THREAD

**Issue by kidsit** [liuyunzhuge/php_weixin_proxy#2]
你好， 
通过header location让微信重定向不起作用，不做跳转。 这种方案是不是现在不可行啊？
是不是必须通过js来设置location方式实现跳转从而获取到code？

**Comment by liuyunzhuge** [comment]
应该还是可行的，我目前的项目仍然在正常使用中。

**Comment by lxalano** [comment]
我使用的过程中也是同样没有跳转回原网页

**Comment by 25ma** [comment]
你好，你的这个工作原理是不是

**Comment by i25ma** [comment]
你好，你的这个项目的工作原理是不是：
1.请求授权代理域名的地址，后将传递过来的redirect_url（业务域名） 存到cookies里面去 
2.然后拼接授权链接获得code，
3. 当获得code之后就将code和state 拼接在业务域名后面，然后重定向到这个业务域名上去
4. 然后再通过code换取access_token 
5.最后通过access_token 获得用户信息

这是我个人的理解，有不正确的还请帮我指正，谢谢

**Comment by kidsit** [comment]
我理解错了，是可以工作的，不好意思，给大家带来误解了
